append  it

diff --git a/jenkins/cicd-docs/build/html/jenkins/pipeline/jenkinsfile_use.html b/jenkins/cicd-docs/build/html/jenkins/pipeline/jenkinsfile_use.html
--- a/jenkins/cicd-docs/build/html/jenkins/pipeline/jenkinsfile_use.html
+++ b/jenkins/cicd-docs/build/html/jenkins/pipeline/jenkinsfile_use.html
@@ -436,6 +436,220 @@ node {
 </ol>
 </div>
 </div>
+<div class="section" id="id9">
+<h2>参数<a class="headerlink" href="#id9" title="Permalink to this headline">¶</a></h2>
+<p>声明式 Pipeline 支持开箱即用的参数，允许 Pipeline 在运行时通过 parameters 指令接受用户指定的参数。使用脚本 Pipeline 配置参数是通过 properties 步骤完成的，可以在代码段生成器中找到。</p>
+<p>如果你使用“使用参数构建”选项来配置 Pipeline 以接收参数，那么这些参数可作为 params 变量的成员访问。
+假设一个名为 “Greeting” 的 String 参数已经在 Jenkinsfile 配置中，它可以通过 ${params.Greeting} 方式访问该参数，示例如下：</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Jenkinsfile (Declarative Pipeline)
+pipeline {
+    agent any
+    parameters {
+        string(name: &#39;Greeting&#39;, defaultValue: &#39;Hello&#39;, description: &#39;How should I greet the world?&#39;)
+    }
+    stages {
+        stage(&#39;Example&#39;) {
+            steps {
+                echo &quot;${params.Greeting} World!&quot;
+            }
+        }
+    }
+}
+</pre></div>
+</div>
+<p>Toggle Scripted Pipeline (Advanced)</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Jenkinsfile (Scripted Pipeline)
+properties([parameters([string(defaultValue: &#39;Hello&#39;, description: &#39;How should I greet the world?&#39;, name: &#39;Greeting&#39;)])])
+
+node {
+    echo &quot;${params.Greeting} World!&quot;
+}
+</pre></div>
+</div>
+</div>
+<div class="section" id="id10">
+<h2>故障处理<a class="headerlink" href="#id10" title="Permalink to this headline">¶</a></h2>
+<p>声明性 Pipeline 默认支持 robust 失败处理经由其 post section，其允许声明许多不同的 “post conditions”，例如：always，unstable，success，failure 和 changed。“Pipelne 语法” 部分提供了有关如何使用各种处置条件的更多详细信息。</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Jenkinsfile (Declarative Pipeline)
+pipeline {
+    agent any
+    stages {
+        stage(&#39;Test&#39;) {
+            steps {
+                sh &#39;make check&#39;
+            }
+        }
+    }
+    post {
+        always {
+            junit &#39;**/target/*.xml&#39;
+        }
+        failure {
+            mail to: team@example.com, subject: &#39;The Pipeline failed :(&#39;
+        }
+    }
+}
+</pre></div>
+</div>
+<p>Toggle Scripted Pipeline (Advanced)</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Jenkinsfile (Scripted Pipeline)
+node {
+    /* .. snip .. */
+    stage(&#39;Test&#39;) {
+        try {
+            sh &#39;make check&#39;
+        }
+        finally {
+            junit &#39;**/target/*.xml&#39;
+        }
+    }
+    /* .. snip .. */
+}
+</pre></div>
+</div>
+<p>但是脚本 Pipeline 依赖于 Groovy 的内置 try/catch/finally 该 pipeline 的执行过程中处理故障的语义。</p>
+<p>在上面的测试示例中，该 sh 步骤被修改为从不返回非零退出代码（sh ‘make check || true’）。这种方法虽然有效，但是意味着以下阶段需要检查 currentBuild。result 以确定是否测试失败。</p>
+<p>处理这种情况的另一种方式是保留 Pipeline 故障的早期退出行为，同时仍然 junit 有机会补货测试报告，是使用一系列 try/finally 代码块</p>
+</div>
+<div class="section" id="id11">
+<h2>使用多个代理<a class="headerlink" href="#id11" title="Permalink to this headline">¶</a></h2>
+<p>在所有以前的例子中，值使用了一个代理。着意味着 Jenkins 将分配一个可用的执行器，无论他是如何标记或配置的。这不仅可以被行为覆盖，但 Pipeline 允许从内利用 Jenkins 环境中的多个代理商相同 Jenkinsfile，可为更高级的使用情况，如执行有帮助建立跨多个平台/测试。</p>
+<p>在下面的示例中，“构建”阶段将在一个代理上执行，并且构建的结果将在“测试”阶段中分别标记为 “linux” 和 “windows” 的两个后续代理程序中重用。</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Jenkinsfile (Declarative Pipeline)
+pipeline {
+    agent none
+    stages {
+        stage(&#39;Build&#39;) {
+            agent any
+            steps {
+                checkout scm
+                sh &#39;make&#39;
+                stash includes: &#39;**/target/*.jar&#39;, name: &#39;app&#39;
+            }
+        }
+        stage(&#39;Test on Linux&#39;) {
+            agent {
+                label &#39;linux&#39;
+            }
+            steps {
+                unstash &#39;app&#39;
+                sh &#39;make check&#39;
+            }
+            post {
+                always {
+                    junit &#39;**/target/*.xml&#39;
+                }
+            }
+        }
+        stage(&#39;Test on Windows&#39;) {
+            agent {
+                label &#39;windows&#39;
+            }
+            steps {
+                unstash &#39;app&#39;
+                bat &#39;make check&#39;
+            }
+            post {
+                always {
+                    junit &#39;**/target/*.xml&#39;
+                }
+            }
+        }
+    }
+}
+</pre></div>
+</div>
+<p>Toggle Scripted Pipeline (Advanced)</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Jenkinsfile (Scripted Pipeline)
+stage(&#39;Build&#39;) {
+    node {
+        checkout scm
+        sh &#39;make&#39;
+        stash includes: &#39;**/target/*.jar&#39;, name: &#39;app&#39;
+    }
+}
+
+stage(&#39;Test&#39;) {
+    node(&#39;linux&#39;) {
+        checkout scm
+        try {
+            unstash &#39;app&#39;
+            sh &#39;make check&#39;
+        }
+        finally {
+            junit &#39;**/target/*.xml&#39;
+        }
+    }
+    node(&#39;windows&#39;) {
+        checkout scm
+        try {
+            unstash &#39;app&#39;
+            bat &#39;make check&#39;
+        }
+        finally {
+            junit &#39;**/target/*.xml&#39;
+        }
+    }
+}
+</pre></div>
+</div>
+<ol class="arabic simple">
+<li>该 <code class="docutils literal notranslate"><span class="pre">stash</span></code> 步骤允许捕获与包含模式（ <code class="docutils literal notranslate"><span class="pre">**/target/*.jar</span></code> ）匹配的文件，以在同一管道中重用。一旦 Pipeline 完成执行，垃圾文件将从 Jenkins 主站中删除。</li>
+<li>agent 中的参数 <code class="docutils literal notranslate"><span class="pre">node</span></code> 允许任何有效的 Jenkins 标签表达式。</li>
+<li><code class="docutils literal notranslate"><span class="pre">unstash</span></code> 将从 Jenkins 主机当前工作空间中检索名为 app 的管道</li>
+<li>该 bat 脚本允许在基于 Windows 的平台上执行批处理脚本。</li>
+</ol>
+</div>
+<div class="section" id="id12">
+<h2>可选步骤参数<a class="headerlink" href="#id12" title="Permalink to this headline">¶</a></h2>
+<p>Pipeline 尊许 Groovy 语言约定，允许在方法参数中省略括号。
+许多 Pipeline 步骤还使用命名参数语法作为使用 Groovy 创建 map 的简写，它使用语法 [key1:value2, key2:value2]。发布如下功能的语句：</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>git url: &#39;git://example.com/amazing-project.git&#39; branch: &#39;master&#39;
+git([url: &#39;git://example.com/amazing-project.git&#39;, branch: &#39;master&#39;])
+</pre></div>
+</div>
+<p>为方便起见，当仅调用一个参数（或只有一个必须参数）时，可能会省略参数名称，例如：</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>sh &#39;echo hello&#39; /* short form */
+sh([script: &#39;echo hello&#39;]) /* long form */
+</pre></div>
+</div>
+</div>
+<div class="section" id="id13">
+<h2>高级脚本管道<a class="headerlink" href="#id13" title="Permalink to this headline">¶</a></h2>
+<p>脚本 Pipeline 是基于 Groovy 的领域专用语言，大多数 Groovy 语法可以在脚本 Pipeline 中使用而无需修改。</p>
+<div class="section" id="id14">
+<h3>同时执行<a class="headerlink" href="#id14" title="Permalink to this headline">¶</a></h3>
+<p>上面的例子在线性系列中的两个不同平台上运行测试。在实践中，如果 make cache 执行需要 30 分钟完成，“测试” 阶段现在需要 60 分钟才能完成！</p>
+<p>幸运的时，Pipeline 具有内置功能，用于并执行 Scripted Pipeline 的部分，在适当命令的 Parallel 步骤中实现。重构上述示例以使用 parallel 步骤：</p>
+<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Jenkinsfile (Scripted Pipeline)
+stage(&#39;Build&#39;) {
+    /* .. snip .. */
+}
+
+stage(&#39;Test&#39;) {
+    parallel linux: {
+        node(&#39;linux&#39;) {
+            checkout scm
+            try {
+                unstash &#39;app&#39;
+                sh &#39;make check&#39;
+            }
+            finally {
+                junit &#39;**/target/*.xml&#39;
+            }
+        }
+    },
+    windows: {
+        node(&#39;windows&#39;) {
+            /* .. snip .. */
+        }
+    }
+}
+</pre></div>
+</div>
+<p>而不是在“linux”和“windows”标签的节点上执行测试，它们现在将在Jenkins环境中存在必需容量的情况下并行执行。</p>
+</div>
+</div>
 </div>
 
 
